#!/bin/sh

. "$TEST_SHELL_PATH/backup/abstract-backup"

shell_unit_test() {
  echo test > "$TEST_TARGET_PATH/lock_pod"
  ! (shell_unit_test_backup)
}

mock kubectl kubectl_mock_overwrite

kubectl_mock_overwrite() {
  mokked
  case "$*" in
    ("get lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --template="*)
    echo '
      HOLDER_IDENTITY=test/'"$(cat "$TEST_TARGET_PATH/lock_pod")"'
      RENEW_TIME='"$(date -u +%Y-%m-%dT%H:%M:%S.%6NZ)"'
      LEASE_DURATION_SECONDS='"$LOCK_DURATION"'
      LEASE_TRANSITIONS=0
      RESOURCE_VERSION=test
      '
    echo wrong-test > "$TEST_TARGET_PATH/lock_pod"
    ;;
    ("get $BACKUP_CRD_NAME -n $CLUSTER_NAMESPACE --template=$BACKUP_CR_TEMPLATE")
    sleep 300
    ;;
    *)
    not_mokked
    ;;
  esac
}
