#!/bin/sh

. "$TEST_SHELL_PATH/backup/abstract-backup"

shell_unit_test() {
  date +%s > "$TEST_TARGET_PATH/lock_timestamp"
  ! (shell_unit_test_backup)
}

mock kubectl kubectl_mock_overwrite

kubectl_mock_overwrite() {
  mokked
  case "$*" in
    ("get lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --template="*)
    # Renew time set to a stamp in the past with a 0-second lease duration so
    # maintain_lock observes the lease expired.
    local PAST_TIME
    PAST_TIME="$(date -u -d "@$(cat "$TEST_TARGET_PATH/lock_timestamp")" +%Y-%m-%dT%H:%M:%S.%6NZ)"
    echo '
      HOLDER_IDENTITY=test/test
      RENEW_TIME='"$PAST_TIME"'
      LEASE_DURATION_SECONDS=0
      LEASE_TRANSITIONS=0
      RESOURCE_VERSION=test
      '
    echo 0 > "$TEST_TARGET_PATH/lock_timestamp"
    ;;
    ("get $BACKUP_CRD_NAME -n $CLUSTER_NAMESPACE --template=$BACKUP_CR_TEMPLATE")
    sleep 300
    ;;
    *)
    not_mokked
    ;;
  esac
}
