#!/bin/sh

. "$TEST_SHELL_PATH/sharded-dbops/abstract-sharded-dbops"

shell_unit_test() {
  EXCLUSIVE_OP=true
  LOCK_SLEEP=0
  date +%s > "$TEST_TARGET_PATH/lock_timestamp"
  ! (shell_unit_test_sharded_dbops)
  check_sharded_dbops_result
}

run_op() {
  sleep 300
}

mock kubectl kubectl_mock_overwrite

kubectl_mock_overwrite() {
  mokked
  case "$*" in
    ("get lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --template="*)
    local PAST_TIME
    PAST_TIME="$(date -u -d "@$(cat "$TEST_TARGET_PATH/lock_timestamp")" +%Y-%m-%dT%H:%M:%S.%6NZ)"
    echo '
      HOLDER_IDENTITY=test/test
      RENEW_TIME='"$PAST_TIME"'
      LEASE_DURATION_SECONDS=0
      LEASE_TRANSITIONS=0
      RESOURCE_VERSION=test
      '
    echo 0 > "$TEST_TARGET_PATH/lock_timestamp"
    ;;
    *)
    not_mokked
    ;;
  esac
}
