#!/bin/sh

. "$TEST_SHELL_PATH/abstract-sharded-dbops"

RUN_SCRIPT_PATH=""
SET_RESULT_SCRIPT_PATH=""
OP_NAME=shardedDbOps
NORMALIZED_OP_NAME='sharded dbops'
KEBAB_OP_NAME='sharded-dbops'

mock kubectl kubectl_mock

shell_unit_test_skip() {
  return 1;
}

kubectl_mock() {
  mokked
  case "$*" in
    ("get lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --template="*)
    echo '
      HOLDER_IDENTITY=test/test
      RENEW_TIME='"$(date -u +%Y-%m-%dT%H:%M:%S.%6NZ)"'
      LEASE_DURATION_SECONDS='"$LOCK_DURATION"'
      LEASE_TRANSITIONS=0
      RESOURCE_VERSION=test
      '
    ;;
    ("patch lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --type merge "*)
    ;;
    ("patch $SHARDED_DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_DBOPS_NAME "*)
    ;;
    ("create --raw /api/v1/namespaces/$CLUSTER_NAMESPACE/events -f"*)
    ;;
    *)
    not_mokked
    ;;
  esac
}
