#!/bin/sh

RETRY_LIMIT=0
SHARDED_CLUSTER_CRD_NAME=sgshardedclusters
SHARDED_CLUSTER_CRD_KIND=SGShardedCluster
CLUSTER_CRD_KIND=SGCluster
CRD_GROUP=stackgres.io
CLUSTER_NAMESPACE=test
SHARDED_CLUSTER_NAME=test
CLUSTER_NAMES='test-coord test-shard0'
SERVICE_ACCOUNT=test
POD_NAME=test
SHARED_PATH="$TARGET_PATH/$TEST_NAME/shared"
LOCAL_BIN_SHELL_UTILS_PATH="$PROJECT_PATH/src/main/resources/templates/shell-utils"
TIMEOUT=1000000
SHARDED_DBOPS_CRD_NAME=sgshardeddbop.stackgres.io
SHARDED_DBOPS_CRD_KIND=SGShardedDbOps
SHARDED_DBOPS_CRD_APIVERSION=stackgres.io/v1
SHARDED_DBOPS_NAME=test
SHARDED_DBOPS_UID=172381f8-3f37-46c9-9a29-8284a73d1e5e
DBOPS_CRD_NAME=sgdbop.stackgres.io
DBOPS_CRD_KIND=SGDbOps
DBOPS_CRD_APIVERSION=stackgres.io/v1
DBOPS_COMPLETED=Completed
DBOPS_FAILED=Failed
DBOPS_LABELS=app=StackGresShardedDbOps,sharded-dbops-name=test
DBOPS_LABELS_JSON='{"app":"StackGresShardedDbOps","sharded-dbops-name":"test"}'
CONDITION_DBOPS_FALSE_RUNNING='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationNotRunning","status":"False","type":"Running"}'
CONDITION_DBOPS_RUNNING='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationRunning","status":"True","type":"Running"}'
CONDITION_DBOPS_FAILED='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationFailed","status":"True","type":"Failed"}'
CONDITION_DBOPS_TIMED_OUT='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationTimedOut","status":"True","type":"Failed"}'
CONDITION_DBOPS_LOCK_LOST='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationLockLost","status":"True","type":"Failed"}'
CONDITION_DBOPS_FALSE_FAILED='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationNotFailed","status":"False","type":"Failed"}'
CONDITION_DBOPS_COMPLETED='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationCompleted","status":"True","type":"Completed"}'
CONDITION_DBOPS_FALSE_COMPLETED='{"lastTransitionTime":"$LAST_TRANSITION_TIME","reason":"OperationNotCompleted","status":"False","type":"Completed"}'
LOCK_LEASE_NAMESPACE=test
LOCK_LEASE_NAME=test
LOCK_DURATION=60
RESOURCE_CRD_NAME="$SHARDED_DBOPS_CRD_NAME"
RESOURCE_NAME="$SHARDED_DBOPS_NAME"

shell_unit_test_skip() {
  return 1;
}

shell_unit_test_sharded_dbops() {
  rm -rf "$SHARED_PATH"
  mkdir -p "$SHARED_PATH"
  SHARED_PATH="$(realpath "$SHARED_PATH")"

  if command -v shell_unit_test_sharded_dbops_init >/dev/null
  then
    shell_unit_test_sharded_dbops_init
  fi

  . "$PROJECT_PATH/src/main/resources/templates/set-sharded-dbops-running.sh"

  rm -f "$SHARED_PATH/create_event.pipe"
  touch "$SHARED_PATH/create_event.pipe"

  . "$PROJECT_PATH/src/main/resources/templates/run-sharded-dbops.sh"

  read_events_service

  . "$PROJECT_PATH/src/main/resources/templates/set-sharded-dbops-result.sh"
}

check_sharded_dbops_result() {
  EXIT_CODE="$?"
  if [ "$EXIT_CODE" != 0 ]
  then
    return "$EXIT_CODE"
  fi
  if ! grep -q '^EXIT_CODE=[0-9]\+$' "$SHARED_PATH/$KEBAB_OP_NAME.out"
  then
    echo "Sharded DbOps terminated without setting EXIT_CODE"
    return 1
  fi
  if ! grep -q '^TIMED_OUT=\(true\|false\)$' "$SHARED_PATH/$KEBAB_OP_NAME.out"
  then
    echo "Sharded DbOps terminated without setting TIMED_OUT"
    return 1
  fi
  if ! grep -q '^LOCK_LOST=\(true\|false\)$' "$SHARED_PATH/$KEBAB_OP_NAME.out"
  then
    echo "Sharded DbOps terminated without setting LOCK_LOST"
    return 1
  fi
}
