#!/bin/sh

. "$TEST_SHELL_PATH/sharded-dbops-major-version-upgrade/abstract-sharded-major-version-upgrade"

shell_unit_test() {
  EXCLUSIVE_OP=true
  BACKUP_PATHS=''
  printf %s ' Completed ' > "$TEST_TARGET_PATH/dbops-test-coord-status"
  printf %s ' Completed ' > "$TEST_TARGET_PATH/dbops-test-shard0-status"
  shell_unit_test_sharded_dbops
  check_sharded_dbops_result || return 1
  grep -q '^  op: majorVersionUpgrade$' "$TEST_TARGET_PATH/created-dbops"
  ! grep -q 'backupPath:' "$TEST_TARGET_PATH/created-dbops"
}
