#!/bin/sh

. "$TEST_SHELL_PATH/abstract-sharded-dbops"

RUN_SCRIPT_PATH="$PROJECT_PATH/src/main/resources/templates/run-sharded-major-version-upgrade.sh"
SET_RESULT_SCRIPT_PATH=""
OP_NAME=majorVersionUpgrade
NORMALIZED_OP_NAME='major version upgrade'
KEBAB_OP_NAME='major-version-upgrade'
POSTGRES_VERSION=16.2
SOURCE_POSTGRES_VERSION=15.5
SG_POSTGRES_CONFIG=postgresconf-16
SOURCE_SG_POSTGRES_CONFIG=postgresconf-15
BACKUP_PATHS='sgbackups.stackgres.io/test/test-coord/16 sgbackups.stackgres.io/test/test-shard0/16'
LINK=false
CLONE=false
CHECK=false
POSTGRES_EXTENSIONS_JSON=''
TO_INSTALL_POSTGRES_EXTENSIONS_JSON=''
MAX_ERRORS_AFTER_UPGRADE=''

shell_unit_test_skip() {
  return 1;
}

shell_unit_test_sharded_dbops_init() {
  rm -f "$TEST_TARGET_PATH/created-dbops"
  rm -f "$TEST_TARGET_PATH/status-patches"
  rm -f "$TEST_TARGET_PATH/sharded-cluster-patches"
}

check_sharded_cluster_dbops_status_removed() {
  grep -qF '{"op":"remove","path":"/status/dbOps"}' "$TEST_TARGET_PATH/sharded-cluster-patches"
}

mock kubectl kubectl_mock

kubectl_mock() {
  mokked
  case "$*" in
    ("get lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --template="*)
    echo '
      HOLDER_IDENTITY=test/test
      RENEW_TIME='"$(date -u +%Y-%m-%dT%H:%M:%S.%6NZ)"'
      LEASE_DURATION_SECONDS='"$LOCK_DURATION"'
      LEASE_TRANSITIONS=0
      RESOURCE_VERSION=test
      '
    ;;
    ("patch lease -n $LOCK_LEASE_NAMESPACE $LOCK_LEASE_NAME --type merge "*)
    ;;
    ("get $SHARDED_CLUSTER_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_CLUSTER_NAME --template="*"sourcePostgresVersion"*)
    printf '%s' "$SOURCE_POSTGRES_VERSION"
    ;;
    ("get $SHARDED_CLUSTER_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_CLUSTER_NAME --template="*)
    cat "$TEST_TARGET_PATH/sharded-cluster-dbops-status-set" 2>/dev/null || true
    ;;
    ("patch $SHARDED_CLUSTER_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_CLUSTER_NAME --type merge "*)
    printf '%s\n' "$*" >> "$TEST_TARGET_PATH/sharded-cluster-patches"
    ;;
    ("patch $SHARDED_CLUSTER_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_CLUSTER_NAME --type json "*)
    printf '%s\n' "$*" >> "$TEST_TARGET_PATH/sharded-cluster-patches"
    ;;
    ("replace --force -f -")
    cat >> "$TEST_TARGET_PATH/created-dbops"
    printf '\n---\n' >> "$TEST_TARGET_PATH/created-dbops"
    echo "$DBOPS_CRD_KIND replaced"
    ;;
    ("get $DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE test-coord --template "*)
    cat "$TEST_TARGET_PATH/dbops-test-coord-status"
    ;;
    ("get $DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE test-shard0 --template "*)
    cat "$TEST_TARGET_PATH/dbops-test-shard0-status"
    ;;
    ("get $DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE -l $DBOPS_LABELS --template "*)
    local CLUSTER
    for CLUSTER in $CLUSTER_NAMES
    do
      printf '%s/%s\n' "$CLUSTER" "$(cat "$TEST_TARGET_PATH/dbops-$CLUSTER-status")"
    done
    ;;
    ("get $SHARDED_DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_DBOPS_NAME --template="*)
    printf '%s' add
    ;;
    ("patch $SHARDED_DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_DBOPS_NAME --type=json "*)
    printf '%s\n' "$*" >> "$TEST_TARGET_PATH/status-patches"
    ;;
    ("patch $SHARDED_DBOPS_CRD_NAME -n $CLUSTER_NAMESPACE $SHARDED_DBOPS_NAME "*)
    ;;
    ("create --raw /api/v1/namespaces/$CLUSTER_NAMESPACE/events -f"*)
    ;;
    *)
    not_mokked
    ;;
  esac
}
